# Generated by Django 3.2.7 on 2021-09-10 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=75, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('reg_number', models.CharField(max_length=12, null=True, unique=True, validators=[users.models.validate_reg])),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SUPERUSER'), (2, 'STAFF'), (3, 'STUDENT'), (4, 'TUTOR')], null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('sender_email', models.EmailField(max_length=100)),
                ('sender_full_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SignUpAccess',
            fields=[
                ('reg_key', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('user_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('user_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to='users.user')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
