# Generated by Django 3.2.7 on 2021-12-02 12:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211202_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[users.models.validate_reg]),
        ),
    ]
